Origin/9 scripts spring jpa das tabelas
NatSatie/letscode-projeto2 pull request #16
Opened 2022-04-06 04:14 UTC by Strizer1

Criação de todas as entidades definidas (Aluno, Professor, Disciplina, Historico, Questao e Alternativa) e seus respectivos repositórios.

2022-04-06 12:33 UTC, NatSatie commented
Muito bom a PR! Só faltou um pequeno detalhe, mas já fizemos um bom avanço 🎉🎉🎉🎉

2022-04-06 17:35 UTC, NatSatie requested changes

2022-04-06 17:35 UTC, NatSatie commented on src/main/java/com/example/letscode/aluno/Aluno.java
> +    private LocalDate data_nascimento;
colocar @Collumn

2022-04-06 17:35 UTC, NatSatie commented on src/main/java/com/example/letscode/aluno/Aluno.java
> +    private LocalDate data_nascimento;
ajustar para camel case

2022-04-06 18:29 UTC, Strizer1 commented on src/main/java/com/example/letscode/aluno/Aluno.java
> +    private LocalDate data_nascimento;
Ajustado ;)

2022-04-07 12:10 UTC, NatSatie approved these changes

2022-04-08 16:01 UTC, merged